version: '3'

services:
  nginx:
    image: nginx:1.17
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./_docker/certbot/conf:/etc/letsencrypt
      - ./_docker/certbot/www:/var/www/certbot
      
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - app
    container_name: pwastas_nginx

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./_docker/certbot/conf:/etc/letsencrypt
      - ./_docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: pwastas_app
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: pwastas
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: pwastas_db
